# Generated by Django 2.0 on 2018-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20180501_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-_dimensions']},
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.IntegerField(blank=True, choices=[(200, 'misc region'), (201, 'geological'), (202, 'vegetation'), (203, 'water'), (204, 'political'), (100, 'misc line'), (101, 'road'), (102, 'river'), (0, 'misc point'), (1, 'settlement'), (2, 'natural'), (3, 'dungeon')], null=True),
        ),
    ]
