# Generated by Django 2.0 on 2018-04-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20180325_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lake',
            name='waterfeature_ptr',
        ),
        migrations.RemoveField(
            model_name='landmass',
            name='geofeature_ptr',
        ),
        migrations.DeleteModel(
            name='MiscFeature',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='geofeature_ptr',
        ),
        migrations.RemoveField(
            model_name='mountainrange',
            name='geofeature_ptr',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='politicalfeature_ptr',
        ),
        migrations.RemoveField(
            model_name='ocean',
            name='waterfeature_ptr',
        ),
        migrations.RemoveField(
            model_name='river',
            name='waterfeature_ptr',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='politicalfeature_ptr',
        ),
        migrations.RemoveField(
            model_name='world',
            name='politicalfeature_ptr',
        ),
        migrations.DeleteModel(
            name='GeoFeature',
        ),
        migrations.DeleteModel(
            name='Lake',
        ),
        migrations.DeleteModel(
            name='Landmass',
        ),
        migrations.DeleteModel(
            name='Mountain',
        ),
        migrations.DeleteModel(
            name='MountainRange',
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
        migrations.DeleteModel(
            name='Ocean',
        ),
        migrations.DeleteModel(
            name='PoliticalFeature',
        ),
        migrations.DeleteModel(
            name='River',
        ),
        migrations.DeleteModel(
            name='Settlement',
        ),
        migrations.DeleteModel(
            name='WaterFeature',
        ),
        migrations.DeleteModel(
            name='World',
        ),
    ]
