# Generated by Django 2.0 on 2018-05-07 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20180501_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance', models.FloatField()),
                ('place1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placepairs_out', to='places.Place')),
                ('place2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placepairs_in', to='places.Place')),
            ],
            options={
                'ordering': ['min_distance'],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='other_places',
            field=models.ManyToManyField(through='places.PlacePair', to='places.Place'),
        ),
    ]
