# Generated by Django 2.0 on 2018-05-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180507_0256'),
        ('places', '0004_auto_20180507_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places_place_owned_set', to='base.Profile'),
            preserve_default=False,
        ),
    ]
