# Generated by Django 2.0 on 2018-03-26 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('patron_of', models.CharField(max_length=255, null=True)),
                ('cleric_domains', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('org_type', models.IntegerField(choices=[(1, 'Family'), (2, 'Religion'), (3, 'Political'), (4, 'Military'), (5, 'Clan'), (99, 'Other')])),
                ('god_followed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower_orgs', to='people.God')),
                ('parent_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orgs', to='people.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('organizations_in', models.ManyToManyField(null=True, related_name='members', to='people.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('sub_population_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_populations', to='people.Population')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='populations_in',
            field=models.ManyToManyField(null=True, related_name='members', to='people.Population'),
        ),
        migrations.AddField(
            model_name='person',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_of_race', to='people.Population'),
        ),
        migrations.AddField(
            model_name='god',
            name='follower_populations',
            field=models.ManyToManyField(related_name='gods_followed', to='people.Population'),
        ),
    ]
