# Generated by Django 2.0 on 2018-03-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='organizations_in',
            field=models.ManyToManyField(related_name='members', to='people.Organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='populations_in',
            field=models.ManyToManyField(related_name='members', to='people.Population'),
        ),
    ]
