# Generated by Django 2.0 on 2018-03-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180326_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_type',
        ),
        migrations.AddField(
            model_name='organization',
            name='member_count',
            field=models.IntegerField(help_text='Including unnamed members not in the database.', null=True),
        ),
    ]
