# Generated by Django 2.0 on 2018-03-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180326_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='member_count',
            field=models.IntegerField(help_text='Including unnamed members not in the database.', null=True),
        ),
    ]
