# Generated by Django 2.0 on 2018-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_population_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='god',
            name='cleric_domains',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='god',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='god',
            name='follower_populations',
            field=models.ManyToManyField(blank=True, related_name='gods_followed', to='people.Population'),
        ),
        migrations.AlterField(
            model_name='god',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='god',
            name='patron_of',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
