# Generated by Django 2.0 on 2018-03-27 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20180326_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='population',
            name='member_count',
            field=models.IntegerField(blank=True, help_text='Including unnamed members not in the database.', null=True),
        ),
        migrations.AlterField(
            model_name='population',
            name='sub_population_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_populations', to='people.Population'),
        ),
    ]
