# Generated by Django 2.0 on 2018-03-30 14:22

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0004_auto_20180329_1757'),
        ('people', '0007_auto_20180327_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combatant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, choices=[('primary', 'blue'), ('info', 'teal'), ('warning', 'yellow'), ('danger', 'red'), ('success', 'green'), ('dark', 'enemy')], max_length=7, null=True)),
                ('initiative', models.IntegerField(blank=True, null=True)),
                ('buffs', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True)),
                ('debuffs', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True)),
                ('other_effects', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True)),
                ('statblock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statblocks.Monster')),
            ],
            options={
                'ordering': ['-initiative'],
            },
        ),
    ]
