# Generated by Django 2.0 on 2018-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_combatant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatant',
            name='id',
        ),
        migrations.AlterField(
            model_name='combatant',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
