# Generated by Django 2.0 on 2018-04-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_combatant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatant',
            name='color',
            field=models.CharField(blank=True, choices=[('primary', 'blue'), ('info', 'light blue'), ('warning', 'yellow'), ('danger', 'red'), ('success', 'green'), ('dark', 'enemy'), ('purple', 'purple'), ('brown', 'brown'), ('orange', 'orange'), ('pink', 'pink')], max_length=7, null=True),
        ),
    ]
