# Generated by Django 2.0 on 2018-04-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dmscreentab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmscreentab',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='dmscreentab',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
