# Generated by Django 2.0 on 2018-05-07 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20180507_0020'),
        ('base', '0004_auto_20180507_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Place'),
        ),
    ]
