# Generated by Django 2.0 on 2018-05-07 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180507_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cur_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cur_campaign_of', to='base.Campaign'),
        ),
    ]
