# Generated by Django 2.0 on 2018-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_cur_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='location_inclusion_distance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
