# Generated by Django 2.0 on 2018-05-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_campaign_location_inclusion_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='location_inclusion_distance',
            new_name='place_inclusion_distance',
        ),
    ]
