# Generated by Django 2.0 on 2018-03-29 17:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0003_auto_20180329_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='alignment',
            field=models.IntegerField(blank=True, choices=[(1, 'lawful good'), (2, 'neutral good'), (3, 'chaotic good'), (4, 'lawful neutral'), (5, 'neutral'), (6, 'chaotic neutral'), (7, 'lawful evil'), (8, 'neutral evil'), (9, 'chaotic evil'), (0, 'unaligned')], null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Common'), (2, 'Dwarvish'), (3, 'Elvish'), (4, 'Giant'), (5, 'Goblin'), (6, 'Orc'), (7, 'Gnomish'), (8, 'Halfling'), (9, 'Abyssal'), (10, 'Celestial'), (11, 'Infernal'), (12, 'Draconic'), (13, 'Sylvan'), (14, 'Primordial'), (15, 'Auran'), (16, 'Aquan'), (17, 'Ignan'), (18, 'Terran'), (19, 'Undercommon'), (20, 'Deep Speech'), (21, 'Druidic'), (22, "Thieve's Cant"), (23, 'Telepathy'), (24, 'Telepathy 30 ft.'), (25, 'Telepathy 60 ft.'), (26, 'Telepathy 120 ft.')], max_length=68, null=True),
        ),
    ]
