# Generated by Django 2.0 on 2018-04-03 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0008_action_attack_tohit_bonus_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialproperty',
            name='save_dc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialproperty',
            name='save_type',
            field=models.CharField(blank=True, choices=[('str', 'strength'), ('dex', 'dexterity'), ('con', 'constitution'), ('int', 'intelligence'), ('wis', 'wisdom'), ('cha', 'charisma')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='specialproperty',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_properties', to='statblocks.Monster'),
        ),
    ]
