# Generated by Django 2.0 on 2018-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0010_action_specific_to_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='generic_name',
            field=models.CharField(blank=True, help_text='If not specified, the name in lowercase will be used.', max_length=255, null=True),
        ),
    ]
