# Generated by Django 2.0 on 2018-04-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0011_monster_generic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-sort_priority']},
        ),
        migrations.AlterModelOptions(
            name='specialproperty',
            options={'ordering': ['-sort_priority']},
        ),
        migrations.AddField(
            model_name='action',
            name='save_dc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='save_type',
            field=models.CharField(blank=True, choices=[('str', 'strength'), ('dex', 'dexterity'), ('con', 'constitution'), ('int', 'intelligence'), ('wis', 'wisdom'), ('cha', 'charisma')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='sort_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='sort_priority',
            field=models.IntegerField(default=0),
        ),
    ]
