# Generated by Django 2.0 on 2018-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0012_auto_20180403_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegendaryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_priority', models.IntegerField(default=0)),
                ('save_dc', models.IntegerField(blank=True, null=True)),
                ('save_type', models.CharField(blank=True, choices=[('str', 'strength'), ('dex', 'dexterity'), ('con', 'constitution'), ('int', 'intelligence'), ('wis', 'wisdom'), ('cha', 'charisma')], max_length=3, null=True)),
            ],
            options={
                'ordering': ['-sort_priority'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_priority', models.IntegerField(default=0)),
                ('save_dc', models.IntegerField(blank=True, null=True)),
                ('save_type', models.CharField(blank=True, choices=[('str', 'strength'), ('dex', 'dexterity'), ('con', 'constitution'), ('int', 'intelligence'), ('wis', 'wisdom'), ('cha', 'charisma')], max_length=3, null=True)),
            ],
            options={
                'ordering': ['-sort_priority'],
            },
        ),
        migrations.AddField(
            model_name='monster',
            name='legendary_actions',
            field=models.ManyToManyField(blank=True, to='statblocks.LegendaryAction'),
        ),
        migrations.AddField(
            model_name='monster',
            name='reactions',
            field=models.ManyToManyField(blank=True, to='statblocks.Reaction'),
        ),
    ]
