# Generated by Django 2.0 on 2018-04-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0013_auto_20180403_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='legendary_actions',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='special_properties',
        ),
        migrations.AddField(
            model_name='action',
            name='monster_set',
            field=models.ManyToManyField(blank=True, related_name='action', to='statblocks.Monster'),
        ),
        migrations.AddField(
            model_name='legendaryaction',
            name='monster_set',
            field=models.ManyToManyField(blank=True, related_name='legendaryaction', to='statblocks.Monster'),
        ),
        migrations.AddField(
            model_name='legendaryaction',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_legendaryaction', to='statblocks.Monster'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='monster_set',
            field=models.ManyToManyField(blank=True, related_name='reaction', to='statblocks.Monster'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_reaction', to='statblocks.Monster'),
        ),
        migrations.AddField(
            model_name='specialproperty',
            name='monster_set',
            field=models.ManyToManyField(blank=True, related_name='specialproperty', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='action',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_action', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_specialproperty', to='statblocks.Monster'),
        ),
    ]
