# Generated by Django 2.0 on 2018-04-04 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0014_auto_20180404_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='monster_set',
            field=models.ManyToManyField(blank=True, related_name='actions', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='action',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_actions', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='legendaryaction',
            name='monster_set',
            field=models.ManyToManyField(blank=True, related_name='legendary_actions', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='legendaryaction',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_legendary_actions', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='monster_set',
            field=models.ManyToManyField(blank=True, related_name='reactions', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_reactions', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='monster_set',
            field=models.ManyToManyField(blank=True, related_name='special_properties', to='statblocks.Monster'),
        ),
        migrations.AlterField(
            model_name='specialproperty',
            name='specific_to_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_properties', to='statblocks.Monster'),
        ),
    ]
