# Generated by Django 2.0 on 2018-04-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statblocks', '0015_auto_20180404_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='monster_set',
        ),
        migrations.RemoveField(
            model_name='action',
            name='specific_to_monster',
        ),
        migrations.RemoveField(
            model_name='legendaryaction',
            name='monster_set',
        ),
        migrations.RemoveField(
            model_name='legendaryaction',
            name='specific_to_monster',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='monster_set',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='specific_to_monster',
        ),
        migrations.RemoveField(
            model_name='specialproperty',
            name='monster_set',
        ),
        migrations.RemoveField(
            model_name='specialproperty',
            name='specific_to_monster',
        ),
        migrations.AddField(
            model_name='action',
            name='statblock_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legendaryaction',
            name='statblock_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='actions',
            field=models.ManyToManyField(blank=True, to='statblocks.Action'),
        ),
        migrations.AddField(
            model_name='monster',
            name='legendary_actions',
            field=models.ManyToManyField(blank=True, to='statblocks.LegendaryAction'),
        ),
        migrations.AddField(
            model_name='monster',
            name='reactions',
            field=models.ManyToManyField(blank=True, to='statblocks.Reaction'),
        ),
        migrations.AddField(
            model_name='monster',
            name='special_properties',
            field=models.ManyToManyField(blank=True, to='statblocks.SpecialProperty'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='statblock_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialproperty',
            name='statblock_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
