# Generated by Django 2.0 on 2018-05-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180507_0256'),
        ('statblocks', '0017_auto_20180404_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statblocks_action_owned_set', to='base.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legendaryaction',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statblocks_legendaryaction_owned_set', to='base.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statblocks_monster_owned_set', to='base.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statblocks_reaction_owned_set', to='base.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialproperty',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statblocks_specialproperty_owned_set', to='base.Profile'),
            preserve_default=False,
        ),
    ]
